/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_cuong_demoopencv_OpenCVClass */
using namespace cv;
#ifndef _Included_com_example_cuong_demoopencv_OpenCVClass
#define _Included_com_example_cuong_demoopencv_OpenCVClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cuong_demoopencv_OpenCVClass
 * Method:    faceDetection
 * Signature: (J)V
 */
void detect(Mat& frame);
JNIEXPORT void JNICALL Java_com_example_cuong_demoopencv_OpenCVClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
